// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJr2MDMBLEzHbM5VDt9QIhr4rIYc7sRW4',
    appId: '1:118894261267:android:3555ef12996338dd3dfbe6',
    messagingSenderId: '118894261267',
    projectId: 'uni-collab-295f0',
    storageBucket: 'uni-collab-295f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuxOga4-OQbMrzPQWM3qCP5Jw59J5Duj0',
    appId: '1:118894261267:ios:6ffcf1277feb6cd13dfbe6',
    messagingSenderId: '118894261267',
    projectId: 'uni-collab-295f0',
    storageBucket: 'uni-collab-295f0.firebasestorage.app',
    androidClientId: '118894261267-9ibd9e5o3hq5vas6ig3a1i2eebl3omv7.apps.googleusercontent.com',
    iosClientId: '118894261267-kul6l8ofdppm9ipebdcadv1qesiqj4br.apps.googleusercontent.com',
    iosBundleId: 'com.asp.collab',
  );
}
